name: Project Request
description: Request new project setup
labels: ["repo", "review", "team", "project"]

body:
  - type: dropdown
    id: team
    attributes:
      label: Select the team
      options:
      - team1

  - type: textarea
    attributes:
      label: free fill txt area
      description: free fill text
    validations:
      required: false
